name: ci
on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '15.x'
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - run: mvn -B package
      - name: Login to GitHub Package Repository
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/arbeidsgiver-notifikasjon-test-produsent:${{ github.sha }}
            ghcr.io/${{ github.repository }}/arbeidsgiver-notifikasjon-test-produsent:latest
          cache-from: type=registry,ref=${{ github.repository }}/arbeidsgiver-notifikasjon-test-produsent:latest
          cache-to: type=inline

      - uses: nais/deploy/actions/deploy@v1
        env:
          IMAGE: ghcr.io/${{ github.repository }}/arbeidsgiver-notifikasjon-test-produsent:${{ github.sha }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais-application.yaml

      - uses: nais/deploy/actions/deploy@v1
        env:
          IMAGE: ghcr.io/${{ github.repository }}/arbeidsgiver-notifikasjon-test-produsent:${{ github.sha }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais-application.yaml
